// Build: inline the pure engine modules into a single self-contained index.html.
//
// Why a build step at all? The engine is written as ES modules so Node can
// import it for tests. Browsers refuse to load ES modules over file://, and
// Voltfin must stay a single file you can double-click or email to a kid. So
// the modules are concatenated into one scope at build time and exposed to the
// shell as `Engine`. There is still no runtime dependency: the output is plain
// HTML/CSS/JS.
//
//   node build.mjs           write index.html from src/
//   node build.mjs --check   fail if index.html is stale (used by npm run check)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));

// Dependency order, shallowest first. Add a module here when you extract one.
const ENGINE_MODULES = [
  "config.js",
  "scoring.js",
  "identity.js",
  "leaderboard.js",
];

const MARKER = "/* @inject:engine */";

const IMPORT_LINE = /^\s*import\s[^;]*;\s*$/gm;
const EXPORT_DECL = /^(\s*)export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)/gm;
const EXPORTED_NAME = /^\s*export\s+(?:async\s+)?(?:function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)/gm;

function bundleEngine() {
  const names = [];
  const bodies = [];

  for (const file of ENGINE_MODULES) {
    const src = readFileSync(join(root, "src/engine", file), "utf8");
    for (const m of src.matchAll(EXPORTED_NAME)) names.push(m[1]);
    const body = src.replace(IMPORT_LINE, "").replace(EXPORT_DECL, "$1").trim();
    bodies.push(`  // ---- src/engine/${file} ----\n` + body.replace(/^/gm, "  "));
  }

  const duplicate = names.find((n, i) => names.indexOf(n) !== i);
  if (duplicate) {
    throw new Error(`engine exports collide on "${duplicate}" — they share one scope after bundling`);
  }

  const bundle = [
    "// Generated by build.mjs from src/engine/ — edit those files, not this block.",
    "const Engine = (() => {",
    bodies.join("\n\n"),
    "",
    `  return { ${names.join(", ")} };`,
    "})();",
  ].join("\n");

  // The bundle shares the shell's scope; any surviving module syntax is a bug.
  if (/^\s*(?:import|export)\s/m.test(bundle)) {
    throw new Error("module syntax survived bundling — build.mjs cannot handle this import/export form");
  }
  return bundle;
}

function build() {
  const shell = readFileSync(join(root, "src/index.html"), "utf8");
  if (!shell.includes(MARKER)) {
    throw new Error(`src/index.html is missing the ${MARKER} marker`);
  }
  const indent = shell.match(new RegExp(`^([ \\t]*)${MARKER.replace(/[*/]/g, "\\$&")}`, "m"))[1];
  const bundle = bundleEngine().replace(/^(?=.)/gm, indent);
  return shell.replace(indent + MARKER, bundle);
}

const out = build();
const target = join(root, "index.html");

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== out) {
    console.error("index.html is out of date — run `npm run build` and commit the result.");
    process.exit(1);
  }
  console.log("index.html is up to date.");
} else {
  writeFileSync(target, out);
  console.log(`Wrote index.html (${ENGINE_MODULES.length} engine module(s) inlined).`);
}
