// Build: inline the pure engine modules into a single self-contained index.html.
//
// Why a build step at all? The engine is written as ES modules so Node can
// import it for tests. Browsers refuse to load ES modules over file://, and
// Voltfin must stay a single file you can double-click or email to a kid. So
// the modules are concatenated into one scope at build time and exposed to the
// shell as `Engine`. There is still no *network* runtime dependency: nothing
// the shipped file needs is ever fetched over HTTP(S) at load or play time.
//
// Since the WebGL renderer (#85), one deliberate offline exception exists:
// PixiJS is vendored at vendor/pixi.min.js — pinned, hash-checked, and
// spliced verbatim into its own <script> block (see readVendorPixi() below),
// never through the regex-based engine bundler and never fetched live. See
// vendor/README.md for the update procedure and CLAUDE.md §1/§8 for why this
// carve-out exists and what it does and doesn't permit.
//
//   node build.mjs                 write the committed web build to index.html
//   node build.mjs --target web    write dist/web/index.html
//   node build.mjs --target app    write dist/app/index.html
//   node build.mjs --check         fail if the committed index.html is stale

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createHash } from "node:crypto";

const root = dirname(fileURLToPath(import.meta.url));

// Dependency order, shallowest first. Add a module here when you extract one.
const ENGINE_MODULES = [
  "config.js",
  "vector.js",
  "movement.js",
  "rng.js",
  "scoring.js",
  "identity.js",
  "leaderboard.js",
  "session.js",
  "bank.js",
  "skins.js",
  "presents.js",
  "minigames.js",
  "progress.js",
  "stats.js",
  "achievements.js",
  "challenges.js",
];

const MARKER = "/* @inject:engine */";
const BUILD_TARGET_MARKER = "/* @inject:build-target */";

const IMPORT_LINE = /^\s*import\s[^;]*;\s*$/gm;
const EXPORT_DECL = /^(\s*)export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)/gm;
const EXPORTED_NAME = /^\s*export\s+(?:async\s+)?(?:function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)/gm;

function bundleEngine() {
  const names = [];
  const bodies = [];

  for (const file of ENGINE_MODULES) {
    const src = readFileSync(join(root, "src/engine", file), "utf8");
    for (const m of src.matchAll(EXPORTED_NAME)) names.push(m[1]);
    const body = src.replace(IMPORT_LINE, "").replace(EXPORT_DECL, "$1").trim();
    bodies.push(`  // ---- src/engine/${file} ----\n` + body.replace(/^/gm, "  "));
  }

  const duplicate = names.find((n, i) => names.indexOf(n) !== i);
  if (duplicate) {
    throw new Error(`engine exports collide on "${duplicate}" — they share one scope after bundling`);
  }

  const bundle = [
    "// Generated by build.mjs from src/engine/ — edit those files, not this block.",
    "const Engine = (() => {",
    bodies.join("\n\n"),
    "",
    `  return { ${names.join(", ")} };`,
    "})();",
  ].join("\n");

  // The bundle shares the shell's scope; any surviving module syntax is a bug.
  if (/^\s*(?:import|export)\s/m.test(bundle)) {
    throw new Error("module syntax survived bundling — build.mjs cannot handle this import/export form");
  }
  return bundle;
}

// The vendored, pinned PixiJS build (see vendor/README.md and vendor-pixi.mjs)
// is spliced in verbatim — never through bundleEngine()'s regex transform,
// which is written only for src/engine/'s hand-authored export style and
// would mangle a real third-party UMD bundle. A pinned SHA-256 in
// vendor/PIXI_VERSION guards against the committed file drifting or being
// hand-edited without going through vendor-pixi.mjs again.
const VENDOR_MARKER = "/* @inject:vendor-pixi */";

function readVendorPixi() {
  const js = readFileSync(join(root, "vendor/pixi.min.js"), "utf8");
  const pinned = readFileSync(join(root, "vendor/PIXI_VERSION"), "utf8").trim();
  const pinnedHash = pinned.match(/sha256:([0-9a-f]{64})/)?.[1];
  if (!pinnedHash) {
    throw new Error("vendor/PIXI_VERSION doesn't contain a sha256:<hex> pin — re-run node vendor-pixi.mjs");
  }
  const actualHash = createHash("sha256").update(js, "utf8").digest("hex");
  if (actualHash !== pinnedHash) {
    throw new Error(
      "vendor/pixi.min.js does not match the pinned hash in vendor/PIXI_VERSION — " +
      "it was hand-edited or drifted. Re-run `node vendor-pixi.mjs` after any legitimate update."
    );
  }
  if (js.includes("<script") || js.includes("</script")) {
    throw new Error("vendor/pixi.min.js contains a literal <script> substring — refusing to splice, it would break the surrounding HTML");
  }
  return js;
}

function build(target) {
  let shell = readFileSync(join(root, "src/index.html"), "utf8");
  if (!shell.includes(MARKER)) {
    throw new Error(`src/index.html is missing the ${MARKER} marker`);
  }
  if (!shell.includes(VENDOR_MARKER)) {
    throw new Error(`src/index.html is missing the ${VENDOR_MARKER} marker`);
  }
  if (!shell.includes(BUILD_TARGET_MARKER)) {
    throw new Error(`src/index.html is missing the ${BUILD_TARGET_MARKER} marker`);
  }

  shell = shell.replace(
    BUILD_TARGET_MARKER,
    () => `const BUILD_TARGET = ${JSON.stringify(target)};`
  );

  // Both splices below use a replacer *function*, not a replacement string.
  // String.prototype.replace(searchString, replacementString) still treats
  // "$&"/"$$"/"$`"/"$'" specially in the replacement even though the search
  // side is a plain string — and vendor/pixi.min.js's 800KB of third-party
  // code genuinely contains a literal "$&" (inside its own regex-escaping
  // helper), which corrupted straight into the marker text the first time
  // this used a plain-string replace. A function's return value is always
  // inserted literally, with no pattern substitution, so this is the only
  // safe form once the injected text isn't hand-written by us.
  const vendorIndent = shell.match(new RegExp(`^([ \\t]*)${VENDOR_MARKER.replace(/[*/]/g, "\\$&")}`, "m"))[1];
  const vendorJs = readVendorPixi().replace(/^(?=.)/gm, vendorIndent);
  shell = shell.replace(vendorIndent + VENDOR_MARKER, () => vendorJs);

  const indent = shell.match(new RegExp(`^([ \\t]*)${MARKER.replace(/[*/]/g, "\\$&")}`, "m"))[1];
  const bundle = bundleEngine().replace(/^(?=.)/gm, indent);
  return shell.replace(indent + MARKER, () => bundle);
}

function requestedTarget(argv) {
  const index = argv.indexOf("--target");
  if (index === -1) return "web";
  const value = argv[index + 1];
  if (value !== "web" && value !== "app") {
    throw new Error('--target must be either "web" or "app"');
  }
  return value;
}

const buildTarget = requestedTarget(process.argv.slice(2));
const out = build(buildTarget);
const explicitTarget = process.argv.includes("--target");
const outputFile = explicitTarget
  ? join(root, "dist", buildTarget, "index.html")
  : join(root, "index.html");

if (process.argv.includes("--check")) {
  const current = readFileSync(outputFile, "utf8");
  if (current !== out) {
    console.error(`${outputFile} is out of date — rebuild it before continuing.`);
    process.exit(1);
  }
  console.log(`${outputFile} is up to date.`);
} else {
  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, out);
  console.log(
    `Wrote ${outputFile} for ${buildTarget} (${ENGINE_MODULES.length} engine module(s) inlined).`
  );
}
